swagger: 2.0
openapi: 3.0.0
info:
  title: Task Organizer
  description: Organize and maintain tasks
  
host: https://lavanyas-5000.theiadocker-1-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai/
basePath: /
schemes:
  - https
paths:
  /tasks:
    get:
      summary: Returns a list of tasks.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
        405:
          description: Invalid Input
